-- DAY 1: JOINING TABLES

-- CALCULATING SCHOOL CAPACITY
-- What's the total capacity of the school?
SELECT SUM(CAPACITY)
FROM ROOMS;

-- THE BIGGEST ROOM
-- Which room has the largest capacity?
SELECT *, MAX(CAPACITY)
FROM ROOMS;

-- SUBJECTS IN THE BIG ROOM
-- Which subject/s are taught in room 19?
SELECT DISTINCT NAME
FROM CLASSES
JOIN SUBJECTS ON CLASSES.SUBJECT_ID = SUBJECTS.ID
WHERE ROOM_ID = 19;

-- 8TH GRADE TEACHERS
-- Which teachers teach only students in 8th grade?
SELECT DISTINCT TEACHERS.ID, FIRST_NAME, LAST_NAME
FROM TEACHERS
JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID
JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
WHERE GRADE = 8;

-- 7TH GRADE TEACHERS
-- Which teacher teaches 7th grade science?
SELECT DISTINCT TEACHERS.ID, FIRST_NAME, LAST_NAME
FROM SUBJECTS
JOIN CLASSES ON SUBJECTS.ID = CLASSES.SUBJECT_ID
JOIN TEACHERS ON TEACHERS.ID = CLASSES.TEACHER_ID
WHERE NAME = "Science" AND GRADE = 7;

-- ELECTIVE TEACHERS
-- Which teachers teach elective subjects (subjects without grade levels)?
SELECT DISTINCT TEACHERS.ID, FIRST_NAME, LAST_NAME 
FROM TEACHERS 
JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID 
JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
WHERE GRADE IS NULL;