-- DAY 2: ADVANCED SELECTING

-- STUDENT SCHEDULE
-- Generate a schedule for Rex Rios.
SELECT PERIOD_ID, NAME, SUBJECTS.GRADE
FROM STUDENTS 
JOIN SCHEDULE ON STUDENTS.ID = SCHEDULE.STUDENT_ID
JOIN CLASSES ON CLASSES.ID = SCHEDULE.CLASS_ID
JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
WHERE FIRST_NAME = 'Rex' AND LAST_NAME = 'Rios'
ORDER BY PERIOD_ID ASC;

-- A SMELLY ISSUE
-- How many students have Physical Education during first period?
SELECT COUNT(*)
FROM STUDENTS
JOIN SCHEDULE ON STUDENTS.ID = SCHEDULE.STUDENT_ID 
JOIN CLASSES ON CLASSES.ID = SCHEDULE.CLASS_ID
JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
WHERE PERIOD_ID = 1 AND NAME = 'Physical Education';

-- STUDENTS A TO M
-- Generate a list of students with last names from A to M.
SELECT *
FROM STUDENTS
WHERE LAST_NAME BETWEEN 'A' AND 'N'
ORDER BY LAST_NAME ASC;

-- STUDENTS BY GRADE
-- How many students are in each grade? And how many 6th graders do you think they'll have next year?
SELECT GRADE, COUNT(*)
FROM STUDENTS
GROUP BY GRADE;

-- PREDICTING THE FUTURE
-- Do they have room for that many 6th graders?
SELECT MIN(CAPACITY) * 7
FROM CLASSES
JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
JOIN ROOMS ON ROOMS.ID = CLASSES.ROOM_ID
WHERE GRADE = 6