-- GETTING GOOD AT GROUPING
-- BUSIEST TEACHERS
-- Which teachers teach a class during all 7 periods?
SELECT TEACHERS.ID, FIRST_NAME, LAST_NAME, COUNT(*)
FROM TEACHERS
JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID
GROUP BY TEACHERS.ID
HAVING COUNT(*) = 7;

-- Do any teachers teach multiple subjects? If so, which teachers?
SELECT TEACHERS.*
FROM TEACHERS
JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID
GROUP BY TEACHERS.ID
HAVING COUNT(DISTINCT SUBJECT_ID) > 1;

-- JANIS' SCHEDULE
-- What class does Janis Ambrose teach during each period? Be sure to include all 7 periods in your report!

WITH JANIS_CLASSES AS (SELECT PERIOD_ID, SUBJECTS.NAME
  FROM TEACHERS
  JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID
  JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
  WHERE TEACHERS.ID = 391)
  
SELECT PERIODS.ID, JANIS_CLASSES.NAME
FROM PERIODS
LEFT OUTER JOIN JANIS_CLASSES ON PERIODS.ID = PERIOD_ID;

-- LEAST POPULAR SUBJECT
-- Which subject is the least popular, and how many students are taking it?
WITH SUBJECT_COUNTS AS (SELECT SUBJECTS.NAME, COUNT(*) 'CT'
  FROM SUBJECTS
  JOIN CLASSES ON SUBJECTS.ID = CLASSES.SUBJECT_ID
  JOIN SCHEDULE ON CLASSES.ID = SCHEDULE.CLASS_ID
  GROUP BY SUBJECT_ID
)
SELECT NAME, MIN(CT) FROM SUBJECT_COUNTS;

-- FINDING THE TROUBLEMAKER
-- Which students have 5th period science and 7th period art?
WITH FIFTH_SCIENCE AS (
  SELECT *
  FROM STUDENTS
  JOIN SCHEDULE ON STUDENTS.ID = SCHEDULE.STUDENT_ID
  JOIN CLASSES ON CLASSES.ID = SCHEDULE.CLASS_ID
  JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
  WHERE PERIOD_ID = 5 AND SUBJECTs.NAME = 'Science'
),
SEVENTH_ART AS (
  SELECT *
  FROM STUDENTS
  JOIN SCHEDULE ON STUDENTS.ID = SCHEDULE.STUDENT_ID
  JOIN CLASSES ON CLASSES.ID = SCHEDULE.CLASS_ID
  JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
  WHERE PERIOD_ID = 7 AND SUBJECTs.NAME = 'Art'
)
  
SELECT C.*
  FROM FIFTH_SCIENCE A
  JOIN SEVENTH_ART B ON A.STUDENT_ID = B.STUDENT_ID
  JOIN STUDENTS C ON A.STUDENT_ID = C.ID


-- MOST POPULAR TEACHER
-- Which elective teacher is the most popular (teaches the most students)?
WITH ELECTIVE_TEACHERS AS (
  SELECT DISTINCT TEACHERS.ID
  FROM TEACHERS 
  JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID 
  JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
  WHERE GRADE IS NULL
),
STUDENT_COUNTS AS (
  SELECT ELECTIVE_TEACHERS.ID, COUNT(*) 'CT'
  FROM ELECTIVE_TEACHERS
  JOIN CLASSES ON ELECTIVE_TEACHERS.ID = CLASSES.TEACHER_ID
  JOIN SCHEDULE ON CLASSES.ID = SCHEDULE.CLASS_ID
  GROUP BY ELECTIVE_TEACHERS.ID
)
SELECT MAX(STUDENT_COUNTS.CT), TEACHERS.FIRST_NAME, TEACHERS.LAST_NAME
FROM STUDENT_COUNTS
JOIN TEACHERS ON STUDENT_COUNTS.ID = TEACHERS.ID

-- BUS TROUBLES
-- Which teachers don't have a class during 1st period?
SELECT TEACHERS.* FROM TEACHERS
EXCEPT
SELECT TEACHERS.*
FROM TEACHERS
JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID
WHERE PERIOD_ID = 1